urls.py
from django.conf.urls.defaults import *
from django.conf import settings
# from ssp.views import main_page
# from django.contrib.auth.decorators import login_required

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('ssp.views',
    url(r'^$', 'main_page', name='main_page'),
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    url(r'about/', 'about_page', name='about_page'),
    url(r'graduated/', 'graduated', name='graduated'),
    url(r'account/', include("reg.urls")),
    url(r'discussion/', include("discussion.urls")),
    url(r'files/', include("files.urls")),
    url(r'events/', include("event.urls")),
    url(r'anketa/', include("anketa.urls")),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

event/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Event(models.Model):
    author=models.ForeignKey(User)
    title=models.CharField(max_length=50)
    description=models.TextField()
    date=models.DateField()
    start_time=models.TimeField()
    def __unicode__(self):
        return self.title
    
class CommentEvent(models.Model):
    author=models.ForeignKey(User)
    event=models.ForeignKey(Event)
    comment=models.TextField()
    created_date=models.DateField(auto_now_add=True) 
    def __unicode__(self):
        return self.comment   

reg/models.py
from django.db import models
from django.db.models import permalink
from django.contrib.auth.models import User
from django.core.files.storage import default_storage
import sha
import random
import re
SHA1_RE = re.compile('^[a-z0-9A-Z]{30}$')
storage = default_storage

class ClientManager(models.Manager):
    def create(self,username,name,surname,email,password):
    	new_user=User.objects.create_user(username,email,password)
    	new_user.is_activate=True
    	new_user.save()
    	client=Client(user=new_user)
        print client
    	client.user_id=new_user.id
    	client.name=name
    	client.surname=surname
        client.activation_key="Activated"
    	client.save()	

class Client(models.Model):
	user=models.ForeignKey(User,unique=True)
	name=models.CharField(max_length=30,blank=True)
	surname=models.CharField(max_length=30,blank=True)
	location=models.CharField(max_length=30,blank=True)
	about=models.CharField(max_length=60,blank=True)
	image = models.ImageField(upload_to="userdata/avatars/", storage=default_storage,blank=True)
	files=models.FileField(upload_to="userdata/files/",blank=True)
	activation_key=models.CharField(('activation_key'),max_length=40,blank=True)
	activated=models.BooleanField(default=False,blank=True)
	create_date = models.DateField(auto_now_add = True,blank=True)
        organizator=models.BooleanField(default=False,blank=True)
        modified_date = models.DateField(auto_now = True,blank=True)
        
	
	objects=ClientManager()

	class Meta:
      	  verbose_name = ('client')
       	  verbose_name_plural = ('clients')
	def __unicode__(self):
		return self.name+" "+self.surname
        @permalink
    	def link_to_self(self):
        	return ('client_profile', (self.id,),)
	@permalink
    	def link_to_edit(self):
        	return ('p_edit', (self.id,),)

	def upload_to_dir(self,filename):
		return 'userdata/files/%s' % (filename)
        
class Entry(models.Model):
    salt=models.CharField(max_length=9)
    registrated=models.BooleanField(default=False)
    def __unicode__(self):
        return self.salt
#	@permalink
#    	def link_to_avatar(self):
 #       return ('account_avatar', (), {})

templates/about.html
{%extends "index.html"%}
{%block top%}
    <div class="meta">
        <div class="metalinks">
            <a href="#"><img src="/media/static/images/meta2.gif" alt="" width="17" height="14" /></a>
            <a href="#"><img src="/media/static/images/meta1.gif" alt="" width="15" height="14" /></a>
            <a href="#"><img src="/media/static/images/meta3.gif" alt="" width="17" height="14" /></a>
            <a href="#"><img src="/media/static/images/meta4.gif" alt="" width="15" height="14" /></a>
        </div>                                                                                                                                                                                                    
    </div>
    
    <div id="header">
        <a href="{%url main_page%}"><img src="/media/static/images/logo-2.jpg" style="float:left;"alt="SDUSummer logo" width="148" height="24" /></a>
        <span class="slogan">Practice Program</span>
    </div>
{%endblock%}
{%block rightinner%}
<div id="home_content">
<h2 id="justi">Программа Университета им. Сулеймана Демиреля</h2>
<h2 id="justi2">"SDU Summer Program"</h2>
<h3>О нас</h3>
<p>Мы являемся группой энтузиастов, состоящей из студентов, преподавателей, а также специалистов в области ИТ, поддерживаемой группой компаний и выпускников. Данная программа запускается второй год, а команда стоящая за ней занимается подобного рода деятельностью уже более 7 лет. Наша работа не выходит за рамки некоммерческой деятельности и направлена исключительно на мирные цели :)</p>
<h3>Цели программы</h3>
<p>Мы хотели бы сблизить компании с ИТ специализацией и образование, наладив сотрудничество на исключительно взаимовыгодных условиях. Программа претерпевает изменения каждый год, с тем чтобы условия сотрудничества между компаниями и ВУЗами было бы актуально каждый год.</p>
<p>Мы убеждены, что успешность образования в области Информационных Технологий, зависит не только от качественного базового образования, но также и от практического опыта приобретенного студентами на всем протяжении обучения. Периодически получая отклики со стороны ведущих компаний страны, а также вовлекая специалистов индустрии делиться знаниями с молодежью мы не только способны постоянно корректировать программу базового образования и задавать верное направление развития знаний преподавательского состава, мы также даём сильную мотивацию и направление учащимся в изучении тех технологий и практик, которые они действительно будут применять на производстве.</p>
<p>Такой выпускник, имеющий хорошую базовую подготовку, имеющий базовые навыки использования современных технологий, а также хороший кругозор будет интересен компаниям, как сотрудник способный быстро включиться в работу, не нуждаясь в длительном сроке «переобучения».</p>
<p>Наша программа — это еще одна возможность компаниям получить хорошие кадры, а ВУЗам лучше готовить будущих специалистов, при отсутсвии каких-либо затрат. Программа 2010 года</p>
<p>Впервые программа была запущена в 2010 году, на участие в программу подало заявления около 70 человек. Из общего количества заявлений было отобрано 30 человек, которые прошли 3-х недельную подготовку, после которой 23 студента были выбраны компаниями для прождения практику в следущих компаниях (после прохождения практики многие ребята продолжили работать в этих компаниях):</p>
<ul>
<li>1.  Казкоммерцбанк, Департамент Инновационных Технологий</li>
<li>2.  BeeSoftware</li>
<li>3.  OneTouchTechnologies</li>
<li>4.  Begusha.kz</li>
<li>5.  KazahTiliKogamy</li>
<li>6.  PrimeSource</li>
<li>7.  BP Solutions</li>
<li>8.  DiamondIT</li>
<li>9.  Simplix</li>
</ul>
<p>Лекции и практические занятия ребятам вели специалисты из таких компаний как BeeSoft, OTT, Simplix, а также GSM Kazakhstan (Kcell).</p>
<h3>Текущие цели программы на 2011 год</h3>
<ul>
<li>1.      Дать возможность лучшим студентам получить производственную практику</li>
<li>2.      Мотивировать студентов к конкурентной борьбе</li>
<li>3.      Узнать текущие требования компаний к подготовке студентов</li>
<li>4.      Повысить качество подготовки студентов</li>
<li>5.      Повысить интерес компаний к программе</li>
</ul>
<h3>Общий процесс</h3>
<ul>
<li>1.      Сбор информации о технологиях, используемых в компаниях, а также определение приоритетных направлений подготовки будущих практикантов.</li>
<li>2.      Набор и подготовка студентов в определенных компаниями приоритетных направлениях, как-то технологии, процессы, стандарты и методологии.</li>
<li>3.      Проведение финального экзамена по истечении срока обучения (с желательным присутствием представителей IT компаний).</li>
</ul>
<p>Первым шагом в программе будет нахождение контактом с компаниями, работающими в сфере производства программного обеспечения, и предоставления им информации о программе. Для обеспечения нормальной деятельности программы в 2010 году мы рассчитываем привлечь от 7 до 10 компаний, для обеспечения 15-18 мест для студентов-практикантов.
</p>
<p>После официального согласия компаний участвовать в программе, мы рассчитываем получить информацию о технологиях, процессах и методологиях используемых этими компаниями в своей ежедневной работе,
а также в которых они заинтересованы в будущем. Эта информация будет использована главным образом для подбора программы обучения студентов-практикантов со стороны СДУ.
</p>
<p>Затем, будет произведен набор студентов в группы по изучаемым технологиям. Хотя мы рассчитываем только на 15 мест для прохождения практики, набор будет произведен из соотношения 1 к 2, т.е. количество
набранных студентов для обучения технологиям будет в два раза больше чем реальное количество мест. Это делается намеренно, для создания внутренней атмосферы конкуренции среди ребят. По окончании обучения ребятами будет проведен экзамен, где принимающей стороной будут как преподаватели, так и представители компаний-партнеров.</p>
<p>Обучать ребят будут как преподаватели из университета, так и профессионалы, активно работающие на данный момент в индустрии.</p>
<p>После проведения финального экзамена 15 из 30 студентов получат возможность пройти производственную практику (а возможно в будущем и работу) в компаниях-партнерах в течении 1-го 2-х месяцев (в
зависимости от требований компаний). После чего компании-партнеры вполне могут предложить место некоторым практикантам.</p>
<p>Во время и после прохождения практики студентами мы рассчитываем получить отзыв от компаний и практикантов о том, как можно было бы улучшить программу в будущем году, так чтобы сделать ее более полезной и привлекательной.</p>
<h3>Привлечение компаний</h3>
<p>В этом году при выборе компаний для предложения участия в программе самым главным принципом для нас является область деятельности компании. Мы рассчитываем работать исключительно с компаниями,
занимающимися производственной деятельностью, т.е. разработкой собственных программных продуктов.
</p>
<h3>Выбор кандидатов из числа студентов</h3>
<p>Для проекта выбираются топ 10% студентов из числа будущих 2-х, 3-х и 4-х курсов. Выбор студентов зависит от многих  факторов. Вот основные:</p>
<p>Очень важным при отборе студентов для нас является мотивация, желание быть успешными и способность работать что называется «день и ночь». Как показывает практика, именно такие ребята бывают действительно успешными в своей карьере.</p>
<h3>Подготовка студентов в соответствии с требованиями компаний</h3>
<p>Для успеха программы необходимо учесть все пожелания и требования компаний-партнеров при подготовке студентов-практикантов. Поэтому, мы планируем разделить всех студентов участвующих в программе на группы по изучаемым предметам. Таким образом, мы постараемся максимально эффективно использовать 2-х недельный период для лучшей подготовки студентов.</p>
<h3>Сроки запуска</h3>
<p>Заявление на участие в программе: принимаются до 15 Мая Также, вам следует заполнить анкету и дополнительно направить письмо по адресу sdu.summer.program@gmail.com. В письме вы должны указать свое ФИО, факультет, курс, группу, достижения (конференции, языки, созданные сайты -- что угодно, что вы считаете собственным достижением). Решение об участниках будет объявлено не позднее 31 Мая Образовательная программа с 1 по 14 июня. Экзамен: 15 -- 16 июня (примерная дата) Производственная практика: индивидуально для каждой компании - от 1-го до 2-х месяцев с 17 июня.</p>
<h3>Заключение</h3>
<p>Поскольку IT индустрия это высоко-динамичная среда, где тенденции и направления меняются ежегодно, всегда существует разрыв между преподаваемыми предметами и реальными требованиями индустрии. Мы
считаем, что подобная программа поможет наладить обратную связь между академической и профессиональной средой, и тем самым не только уменьшить этот разрыв, но и предоставлять более квалифицированные кадры компаниям, делая свой вклад в развитие IT индустрии</p>
</div>
{%endblock%}

templates/avatar.html
{%extends "client_page.html"%}
{%block content%}
Choose your avatar
<form method="POST" action="{%url avatar%}" accept-charset="utf-8" enctype="multipart/form-data">{%csrf_token%}
{{avatar.as_p}}
<input type="submit" value="submit">
</form>
{%endblock%}

templates/client_page.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>SDU Summer Practice Program</title>
<meta name="keywords" content="SDU Summer Practice Program Летняя практика в СДУ." />
<meta name="description" content="Сайт для студентов СДУ и работодателей" />

<link type="text/css" href="/media/static/js/themes/smoothness/jquery-ui.css" rel="Stylesheet" />	
<script type="text/javascript" src="/media/static/js/jquery-1.5.2.min.js"></script>
<script type="text/javascript" src="/media/static/js/jquery-ui-1.8.13.custom.min.js"></script>
<script type="text/javascript" src="/media/static/js/jcarousel/lib/jquery.jcarousel.min.js"></script>
<link rel="stylesheet" type="text/css" href="/media/static/js/jcarousel/skins/tango/skin.css" />
<link href="/media/static/master.css" rel="stylesheet" type="text/css" />
<script src="/media/static/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		// General options
		mode : "textareas",
		theme : "advanced",
		//plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",
		plugins : 'inlinepopups',
		theme_advanced_buttons1 : "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,bullist,numlist,undo,redo,link,unlink",
    	theme_advanced_buttons2 : "",
     	theme_advanced_buttons3 : "",
		// Theme options
		//theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
		//theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		//theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		//theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,

		// Example content CSS (should be your site CSS)
		content_css : "/media/static/js/tinymce/examples/css/content.css",

		// Drop lists for link/image/media/template dialogs
		//template_external_list_url : "lists/template_list.js",
		//external_link_list_url : "lists/link_list.js",
		//external_image_list_url : "lists/image_list.js",
		//media_external_list_url : "lists/media_list.js",

		// Style formats
		style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Example 1', inline : 'span', classes : 'example1'},
			{title : 'Example 2', inline : 'span', classes : 'example2'},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],

		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	});
</script>
<script type="text/javascript">
$(document).ready(function() {
$("div.sup").hide();

$("div#dis_mini, div#eve_mini").mouseenter(function(){
$(this).css('background-color','#fbfbfb');
$(this).find('div.sup').fadeIn("normal");
});
$("div#dis_mini, div#eve_mini").mouseleave(function(){
$(this).css('background-color','white');
$(this).find('div.sup').hide();
			}
);
$('#mycarousel').jcarousel();

});

</script>
<script src="/media/static/js/ui/jquery.ui.datepicker.js" type="text/javascript"></script>

</head>
<body>
{% block top%}
	<div class="meta">

		<div class="metalinks">
        	<a href="#"><img src="/media/static/images/meta2.gif" alt="" width="17" height="14" /></a>
			<a href="#"><img src="/media/static/images/meta1.gif" alt="" width="15" height="14" /></a>
			<a href="#"><img src="/media/static/images/meta3.gif" alt="" width="17" height="14" /></a>
			<a href="#"><img src="/media/static/images/meta4.gif" alt="" width="15" height="14" /></a>
		</div>																																																	
	</div>
	
	<div id="header">
		<a href=""><img src="/media/static/images/logo-2.jpg" style="float:left;"alt="SDUSummer logo" width="148" height="24" /></a>
		<span class="slogan">Practice Program</span>


<ul id="menu">
			<li><a href="{%url home_profile %}" accesskey="1" title="">Основное </a></li>
			<li><a href="{%url client_profile user.id%}" accesskey="2" title="">Мой профиль</a></li>
			<li><a href="{%url members%}" accesskey="3" title="">Участники</a></li>
			<li><a href="{%url dis_list%}" accesskey="4" title="">Дискуссии</a></li>
			<li><a href="{%url events_list%}" accesskey="6" title="">События</a></li>
			{%if user.get_profile.organizator%}
			<li><a href="{%url anketa_list%}" accesskey="8">Анкеты</a></li>
			{%endif%}
			<li class="last"><a href="{%url file_list%}" accesskey="5" title="">Файлы</a></li>
		</ul>
	</div>
{%endblock%}

<div id="content1">
<div id="inner_content">

{%block content%}
{%endblock%}
	

{%block right%}	
<!--панель управления-->
<div id="rightside" style="float:right;">
<div class="forum-panel">
	{%for c in user.client_set.all %}
	<h3>{{c}}</h3>
	{%endfor%}
	<ul>
		<li><a href="{%url logout%}" title="выйти">Выйти</a></li>
        <li><a href="{%url client_profile user.id%}" title="изменить профиль">Профиль</a></li>        		
	</ul>
	<h3>Мои посты</h3>
    <ul>
    {%for d in user.discussion_set.all%}
	   <li><span class="ico dis"></span><a href="{%url dis_detail d.id%}">{{d}}({{d.comment_set.count}})</a></li>
	{%endfor%}
    </ul>
    <h3>Мои события</h3>
    <ul>
    {%for e in user.event_set.all%}
	   <li><span class="ico event"></span><a href="{%url event_detail e.id%}">{{e}}({{e.commentevent_set.count}})</a></li>
	{%endfor%}
    </ul>
    <h3>Добавить</h3>
	<ul>
        <li><span class="ico dis"></span><a href="{%url create_dis%}" title="создать новую тему">Пост</a></li>
		<li><span class="ico event"></span><a href="{%url event_create%}" title="создать событие">Событие</a></li>
		<li><span class="ico file_add"></span><a href="{%url upload_file%}" title="добавить новый файл">Файл</a></li>
    </ul>
    
</div>
</div>

<div class="clear"></div>
{%endblock%}
{%block footer%}	
		<div id="info">
        <!--for parteners-->
			<div id= "leftdiv">
				<h2>Наши партнеры</h2>
				<ul>
					<li><a href="http://p-s.kz/"><img id="logoimg" src="/media/static/images/logos/p-s.png" alt="primesource" /></a></li>
					<li><a href="http://www.bee.kz/about_careers.html"><img id="logoimg" src="/media/static/images/logos/beesoft.png" alt="beesoftware"/></a></li>
					<li><a href="http://www.kkb.kz/"><img id="logoimg" src="/media/static/images/logos/kazkom.jpg" alt=""/></li>
					<li><a href="http://bpsolutions.kz/"><img id="logoimg" src="/media/static/images/logos/bpsolutions.png" alt=""/></a></li>
					<li><a href="http://ott.kz/"><img id="logoimg" src="/media/static/images/logos/ott.png" alt=""/></a></li>
					<li><a href="http://begusha.kz/"><img id="logoimg" src="/media/static/images/logos/begusha.png" alt=""/></a></li>
				</ul>
			</div>
			<div id ="rightdiv">
				<h2>Контакты</h2>
				<ul>
					<li>По вопросам обращайтесь по следующим контактам:</li>
					<li>anzor.israilov@gmail.com</li>
					<li>tasalta@gmail.com</li>
					<li>zhakaarai@gmail.com</li>
					<li>Телефоны:</li>
					<li>87014377474(Арайлым), 87015527795(Салтанат)</li>
				</ul>
			</div>
		</div>
{%endblock%}
</div>
</div>
<div id="footer">
	<p>Almaty 2011</p>
</div>
</body>
</html>

templates/client_profile.html
{%extends "client_page.html"%}
{% block content%}
<div id="content2">
<h1><span>My Profile {{client.username}}</span></h1>
		

<table>
<tr>
{%if client.image%}
<td><img width="48" src="{{client.image.url}}"></td>
{%else%}
<td><img src="/media/static/images/per.png"></td>
{%endif%}
</td>
{%if client.name%}
<td>Name:</td>	<td>{{client.name}}</td>
{%else%}
<td>Name:</td>	<td>{{client.name}}</td>
{%endif%}
</tr>
<tr>
{%if client.surname%}
<td></td><td>Surname:</td><td>{{client.surname}}</td>
{%else%}
<td>Surname:</td><td>None</td>
{%endif%}
</tr>
<tr>
</tr>

<tr>
{%if client.location%}
<td></td><td>Location:</td><td>{{client.location}}</td>
{%else%}
<td></td><td>Location:</td>	<td>You haven't fill yet</td>
{%endif%}

</tr>
<tr>
</tr>

<tr>
{%if client.about%}
<td></td><td>About:</td><td>{{client.about}}</td>
{%else%}
<td></td><td>About:</td>	<td>You haven't fill yet</td>
{%endif%}


</tr>
<tr>
</tr>


<tr>
{%if client.files%}
<td></td><td>Cv:</td><td>{{client.files}}</td>
{%else%}
<td></td><td>Cv:</td><td>You didn't dowload</td>
{%endif%}
</tr>
<tr>
</tr>



<tr>
<td></td><td>Create date:</td><td>{{client.create_date}}</td>
</tr>
<tr>
</tr>

<tr>
<td></td><td>Modified date:</td><td>{{client.modified_date}}</td>
</tr>

<tr>
</tr>


<td></td><td></td><td><a href="{{client.link_to_edit}}">Edit</a></td>{%csrf_token%}
</tr>
</table>
					</div>
	</div>


{% endblock %}

templates/cv.html
{%extends "index.html"%}
{%block content%}
Choose your avatar
<form method="POST" action="" accept-charset="utf-8" enctype="multipart/form-data">{%csrf_token%}
{{cv.as_p}}
<input type="submit" value="upload">
</form>
{%endblock%}

templates/home_profile.html
{%extends "client_page.html"%}
{%block content%}
<div id= "content2">
	<h1><span>Новые события</span></h1>  
	<div class=" jcarousel-skin-tango"><div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block; "><div class="jcarousel-clip jcarousel-clip-horizontal" style="position: relative; "><ul id="mycarousel" class="jcarousel-list jcarousel-list-horizontal" style="overflow-x: hidden; overflow-y: hidden; position: relative; top: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; width: 950px; left: 0px; ">
	{%for e in events%}
	<li class="jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal" style="float: left; list-style-type: none; list-style-position: initial; list-style-image: initial; " jcarouselindex="1"><div id="eve_mini">
    <h2 class="title"><a href="{%url event_detail e.id%}">{{e}}</a></h2>
    <p>{{e.date}} {{e.start_time}}</p>
    <span class="created spanpos"> Автор: <a href="{%url withoutedit e.author.id%}">{{e.author}}</a>  {{e.commentevent_set.count}} отзывов</span>
    {% ifequal user.id e.author.id %}
    <div class="sup">
    <ul>
    <li class="left"><span class="ui-icon ui-icon-pencil"></span></li>
    <li class="left"><a href="{%url event_edit e.id %}">ред.</a></li>
    <li class="left"><span class="ui-icon ui-icon-close"></span></li>
    <li class="left"><a href="{%url event_delete e.id %}">удалить</a></li>
    </ul>
    </div>
    {% endifequal %}
    </div></li>
	{%endfor%}  
	</ul></div><div class="jcarousel-prev jcarousel-prev-horizontal jcarousel-prev-disabled jcarousel-prev-disabled-horizontal" style="display: block; " disabled="true"></div><div class="jcarousel-next jcarousel-next-horizontal" style="display: block; " disabled="false"></div></div></div>
    

	
    <h1><span>Новые дискуссии</span></h1>
    {%for dis in diss%}
    <div id="dis_mini">
    {% with dis.author.get_profile.image as image %}
    {% if image %}
        <img width="48" src="{{ image.url }}">
    {% else %}
        <img src="/media/static/images/per.png">
    {% endif %}
    {% endwith %}
    <h2 class="title"><a href="{%url dis_detail dis.id%}">{{dis}}</a></h2>
    <p>{{ dis.description|safe|truncatewords_html:20 }}</p>
    <span class="created spanpos">Created by:<a href="{%url withoutedit dis.author.id%}">{{dis.author}}</a>-{{dis.create_date}}-{{dis.comment_set.count}} comment</span>
    {% ifequal user.id dis.author.id %}
    <div class="sup">
    <ul>
    <li class="left"><span class="ui-icon ui-icon-pencil"></span></li>
    <li class="left"><a href="{%url dis_edit dis.id %}">ред.</a></li>
    <li class="left"><span class="ui-icon ui-icon-close"></span></li>
    <li class="left"><a href="{%url dis_delete dis.id %}">удалить</a></li>
    </ul>
    </div>
    {% endifequal %}
    </div>
    
    
{%endfor%}
</div>
{%endblock%}


templates/members.html
{%extends "client_page.html"%}
{%block content%}
<div id= "content2">
<h1><span>Members</span></h1>
<table>
{%for member in members%}
	<tr>
		{%if member.image%}
			<td><img width="48" src="{{member.image.url}}"></td>
		{%else%}
			<td><img src="/media/static/images/per.png"></td>
		{%endif%}
		<td><a href="{%url withoutedit member.user.id%}">{{member}}</a></td>
	</tr>
{%endfor%}
</table>
</div>
{%endblock%}

templates/profile_edit.html
{%extends "client_page.html"%}
{%block content%}
<div id= "content2">
<h1><span>Edit profile</span></h1>
<table>
<tr>
{%if client.image%}
<td><img width="48" src={{client.image.url}}></td>
{%else%}
<td><img  src="/media/static/images/per.png"></td>
{%endif%}
<td><a width="48" href="{%url avatar %}">Change</a></td>
</tr>
<form method="post" action="" accept-charset="utf-8" enctype="multipart/form-data">{% csrf_token %}
{{form.as_table}}
<tr>
<td></td><td><input type="submit" value="save"></td>
</tr>
</form>

</table>
</div>
{%endblock%}