event/urls.py
from django.conf.urls.defaults import *
from event.views import *
from django.conf import settings
urlpatterns = patterns('event.views',
    url(r'this_event/(\d+)/$', 'event_detail', name = 'event_detail'),
    url(r'create_event/$', 'event_create', name = 'event_create'),
    url(r'event/', 'events_list', name = 'events_list'),
    url(r'edit/(\d+)$', 'event_edit', name = 'event_edit'),
    url(r'delete/(\d+)$', 'event_delete', name = 'event_delete'),
    
    
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
# from ssp.views import main_page
# from django.contrib.auth.decorators import login_required

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('ssp.views',
    url(r'^$', 'main_page', name='main_page'),
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    url(r'about/', 'about_page', name='about_page'),
    url(r'graduated/', 'graduated', name='graduated'),
    url(r'account/', include("reg.urls")),
    url(r'discussion/', include("discussion.urls")),
    url(r'files/', include("files.urls")),
    url(r'events/', include("event.urls")),
    url(r'anketa/', include("anketa.urls")),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

event/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Event(models.Model):
    author=models.ForeignKey(User)
    title=models.CharField(max_length=50)
    description=models.TextField()
    date=models.DateField()
    start_time=models.TimeField()
    def __unicode__(self):
        return self.title
    
class CommentEvent(models.Model):
    author=models.ForeignKey(User)
    event=models.ForeignKey(Event)
    comment=models.TextField()
    created_date=models.DateField(auto_now_add=True) 
    def __unicode__(self):
        return self.comment   

reg/models.py
from django.db import models
from django.db.models import permalink
from django.contrib.auth.models import User
from django.core.files.storage import default_storage
import sha
import random
import re
SHA1_RE = re.compile('^[a-z0-9A-Z]{30}$')
storage = default_storage

class ClientManager(models.Manager):
    def create(self,username,name,surname,email,password):
    	new_user=User.objects.create_user(username,email,password)
    	new_user.is_activate=True
    	new_user.save()
    	client=Client(user=new_user)
        print client
    	client.user_id=new_user.id
    	client.name=name
    	client.surname=surname
        client.activation_key="Activated"
    	client.save()	

class Client(models.Model):
	user=models.ForeignKey(User,unique=True)
	name=models.CharField(max_length=30,blank=True)
	surname=models.CharField(max_length=30,blank=True)
	location=models.CharField(max_length=30,blank=True)
	about=models.CharField(max_length=60,blank=True)
	image = models.ImageField(upload_to="userdata/avatars/", storage=default_storage,blank=True)
	files=models.FileField(upload_to="userdata/files/",blank=True)
	activation_key=models.CharField(('activation_key'),max_length=40,blank=True)
	activated=models.BooleanField(default=False,blank=True)
	create_date = models.DateField(auto_now_add = True,blank=True)
        organizator=models.BooleanField(default=False,blank=True)
        modified_date = models.DateField(auto_now = True,blank=True)
        
	
	objects=ClientManager()

	class Meta:
      	  verbose_name = ('client')
       	  verbose_name_plural = ('clients')
	def __unicode__(self):
		return self.name+" "+self.surname
        @permalink
    	def link_to_self(self):
        	return ('client_profile', (self.id,),)
	@permalink
    	def link_to_edit(self):
        	return ('p_edit', (self.id,),)

	def upload_to_dir(self,filename):
		return 'userdata/files/%s' % (filename)
        
class Entry(models.Model):
    salt=models.CharField(max_length=9)
    registrated=models.BooleanField(default=False)
    def __unicode__(self):
        return self.salt
#	@permalink
#    	def link_to_avatar(self):
 #       return ('account_avatar', (), {})

event/forms.py
from django import forms
from event.models import *
from event.forms import *

class EventForm(forms.ModelForm):
    class Meta:
        model=Event
        exclude=('author')
class EventCommentForm(forms.ModelForm):
    class Meta:
        model=CommentEvent
        exclude=('event','author')
        

event/views.py
from event.models import *
from event.forms import *

from django.shortcuts import render_to_response 
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

@login_required
def events_list(request):
    events=Event.objects.all()
    rc=RequestContext(request,{'events':events})
    return render_to_response("events/events_list.html",rc)
@login_required
def event_detail(request,event_id):
    event=Event.objects.get(id=event_id)
    com= CommentEvent(event=event,author=request.user)
    print com
    if request.method=="POST":
        ce= EventCommentForm(request.POST,instance=com)
        if ce.is_valid():
            ce.save()
            return HttpResponseRedirect(reverse('event_detail',args=(event_id,)))
    else:
        ce= EventCommentForm(instance=com)
        print ce
    rc=RequestContext(request,{'cform':ce,'event':event})
    return render_to_response("events/event_detail.html",rc)
@login_required
def event_create(request):
    event=Event(author=request.user)
    if request.method=="POST":
        eform=EventForm(request.POST,instance=event)    
        if eform.is_valid():
            eform.save()
            return HttpResponseRedirect(reverse('event_detail',args=(event.id,)))
    else:
        eform=EventForm(instance=event)
    rc=RequestContext(request,{'eform':eform})
    return render_to_response("events/event_create.html",rc)
@login_required
def event_edit(request,event_id):
    event=Event.objects.get(id=event_id)
    if request.user==event.author:
        if request.method=="POST":
            eform=EventForm(request.POST,instance=event)
            if eform.is_valid():
                eform.save()
                return HttpResponseRedirect(reverse("event_detail",args=(event.id,)))
        else:
            eform=EventForm(instance=event)
        rc=RequestContext(request,{'eform':eform})
        return render_to_response("events/event_create.html",rc)
    else:
        return HttpResponseRedirect(reverse("event_detail",args=(event.id,)))
@login_required    
def event_delete(request,event_id):
    event=Event.objects.get(id=event_id)
    if request.user==event.author:
        event.delete()
    return HttpResponseRedirect(reverse("events_list"))

templates/events/event_create.html
{%extends "client_page.html"%}
{%block content%}
<div id= "content2">
    <h1><span>Новое событие</span></h1>
<h2>Create Event</h2>
<form action="" method="post">{%csrf_token%}
{{eform.as_p}}		

<script>
$(function() {
$( "#id_date" ).datepicker();
});
</script>
		<input type='submit' value='create' />
	</form>
</div>
{%endblock%}

templates/events/event_detail.html
{%extends "client_page.html"%}
{%block content%}
<div id= "content2">
    <h1><span>Детали События</span></h1>
<div id="dis_mini">
<h2 class="title">{{event|safe}}</h2>
<div id="date_time">Дата начала:{{event.date}} в {{event.start_time}}</div>
{{event.description|safe}}

<span class="created spanpos">Приглашает на событие: <a href="{%url withoutedit event.author.id%}">{{event.author}}</a>  {{event.commentevent_set.count}} комментариев</span>
{% ifequal user.id event.author.id %}
    <div class="sup">
    <ul>
    <li class="left"><span class="ui-icon ui-icon-pencil"></span></li>
    <li class="left"><a href="{%url event_edit event.id %}">ред.</a></li>
    <li class="left"><span class="ui-icon ui-icon-close"></span></li>
    <li class="left"><a href="{%url event_delete event.id %}">удалить</a></li>
    </ul>
    </div>
{% endifequal %}
</div>
<h1>Комментарии</h1>
{%for comment in event.commentevent_set.all%}
<div class="comments">
{% with comment.author.get_profile.image as image %}
{% if image %}
<img src="{{ image.url }}">
{% else %}
<img src="/media/static/images/per.png">
{% endif %}
{% endwith %}
<div id="text">
<a href="{%url withoutedit event.author.id%}">{{comment.author.client_set.get}}</a> 
{{comment|safe}}
<div id="date_mini">{{comment.created_date}}</div>
</div>
</div>
{%empty%}
No Comment
{% endfor %}
{% if user.is_authenticated %}
<form action="" method="post">{%csrf_token%}
{{cform.as_p}}
<input type='submit' value='post' />
</form>
</div>
{%endif%}
{%endblock%}

templates/events/events_list.html
{%extends "client_page.html"%}
{%block content%}
<div id= "content2">
    <h1><span>Все события</span></h1>
    {%for e in events%}
    <div id="dis_mini">
    <h2 class="title"><a href="{%url event_detail e.id%}">{{e}}</a></h2>
    <p>{{ e.description|safe|truncatewords_html:20 }}</p>
    {% ifequal user.id e.author.id %}
    <div class="sup">
    <ul>
    <li class="left"><span class="ui-icon ui-icon-pencil"></span></li>
    <li class="left"><a href="{%url event_edit e.id %}">ред.</a></li>
    <li class="left"><span class="ui-icon ui-icon-close"></span></li>
    <li class="left"><a href="{%url event_delete e.id %}">удалить</a></li>
    </ul>
    </div>
    {% endifequal %}
    <span class="created spanpos"> Автор: <a href="{%url withoutedit e.author.id%}">{{e.author}}</a>  {{e.commentevent_set.count}} отзывов</span>
    </div>
{%endfor%}
</div>
{%endblock%}